annotate_vcf: true
annotation_tools:
- vep
cram_instead_of_bam_output: false
germline_tools: ''
input_data_format: fastq
max_cpus: 24
max_mem_GB: 120
max_runtime: 02-00:00:00
mode: wgs
run_directory_name: seqc2_align
slurm_email: ''
somatic_tools: ''
start_at: mapping
stop_after: alignment
target_bed: ''
umi_structure: ''
